### ISSUE TITLE
Please explain how this works

### ISSUE THREAD

**Issue by Deadtrix21** [cazzwastaken/pro-bhop#1]
Hmmmm
Not an issue but since ur English
And everything

Mind explaining me how this works
Like i can see the code and everything but I'd like someone to explain why and where 

I am building something similar or want to but it's not a cheat

**Comment by cazzwastaken** [comment]
Essentially, we use the WindowsAPI to get the process ID of the game by creating a snap shot of all the processes running on the system and comparing the executable names. In this case, we search for "csgo.exe" and grab the process ID.

Once we have the process ID we can open a handle to the game with PROCESS_ALL_ACCESS to allow us to Read/Write memory.

All of this is wrapped into a simple class called Memory in this source. Once we have the handle, we make use of offsets added onto the base address of the game's modules (module addresses found in a similar way to process ID above) to get addresses of data in game and then we use Read/WriteProcessMemory to modify said data and create our cheats. Hope that makes sense.
Cheers, cazz~
